---
apiVersion: v1
kind: ConfigMap
metadata:
   name: nwapp-cm 
   labels:
      app: northwind

data:
   DB_USER: root
   DB_HOST: nwdb-svc.nwapp.svc.cluster.local

---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: nwapp-deploy
   labels:
      app: northwind

spec:
   replicas: 2
   selector:
      matchLabels:
         app: nwapp-pod
   strategy:
      type: RollingUpdate
      rollingUpdate:
         maxSurge: 1
         maxUnavailable: 1
   template:
      metadata:
         name: nwapp-pod 
         labels:
            app: nwapp-pod
      spec:
         containers:
         - name: nwapp-container
           image: chukmunnlee/nwapp:v1
           imagePullPolicy: IfNotPresent
           resources:
              requests:
                 cpu: 100m
           env:
           - name: DB_USER
             valueFrom:
                configMapKeyRef:
                   name: nwapp-cm 
                   key: DB_USER
           - name: DB_HOST
             valueFrom:
                configMapKeyRef:
                   name: nwapp-cm 
                   key: DB_HOST
           - name: DB_PASSWORD 
             valueFrom:
                secretKeyRef:
                   name: nwdb-secret
                   key: MYSQL_ROOT_PASSWORD
           - name: INSTANCE_IP_ADDRESS 
             valueFrom:
                fieldRef:
                   fieldPath: status.podIP
           ports:
           - name: nwapp-port
             containerPort: 3000
           livenessProbe:
              initialDelaySeconds: 5
              periodSeconds: 30
              timeoutSeconds: 5
              failureThreshold: 3
              httpGet:
                 path: /health
                 port: nwapp-port
---
apiVersion: v1
kind: Service
metadata:
   name: nwapp-svc
   labels:
      app: northwind

spec:
   type: ClusterIP
   selector:
      app: nwapp-pod
   ports:
   - name: app-port
     port: 8080
     targetPort: nwapp-port

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
   name: nwapp-hpa
   labels:
      app: northwind

spec:
   minReplicas: 2
   maxReplicas: 5
   targetCPUUtilizationPercentage: 20
   scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: nwapp-deploy
