apiVersion: v1
kind: PersistentVolume
metadata:
   name: wp-nfs-pv
spec:
   accessModes:
   - ReadWriteMany
   - ReadMany
   resources:
      requests:
         storage: 100Gi
   nfs:
      server: mynfsserver.com
      path: /share

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: wp-nfs-pvc
spec:
   accessModes:
   - ReadWriteMany
   resources:
      requests:
         storage: 99Gi
   volumeName: wp-nfs-pv

---

